name: recruit-crawler-back
app: node@18
resources: {}
options:
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "3005"
  ports: "3005"
  install: npm ci --production
  start: npm start
  healthz: /health-check
context:
  git:
    url: https://github.com/minr2kb/recruit-crawler-back.git
    branch: main
